remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jemoji
  - jekyll-remote-theme
title: [ArcadiaOS]
description: [A custom rom based on crDroid an LineageOS with extra fitures]
relative_links:
  enabled: true
  collections: true
include:
  - changelog.html
  - devices.html
